export const endpoints = {
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    setupStatus: "/auth/setup-status",
    setup: "/auth/setup",
  },
  admin: {
    account: "/admin/account",
    cashiers: "/admin/cashiers",
    cashierById: (cashierId: string) => `/admin/cashiers/${cashierId}`,
    cashierDisable: (cashierId: string) => `/admin/cashiers/${cashierId}/disable`,
    cashierEnable: (cashierId: string) => `/admin/cashiers/${cashierId}/enable`,
    cashierFinishSession: (cashierId: string) =>
      `/admin/cashiers/${cashierId}/sessions/finish`,
    cashierWhatsappSessions: (cashierId: string) => `/admin/cashiers/${cashierId}/whatsapp-sessions`,
    whatsappSession: (sessionId: string) => `/admin/whatsapp-sessions/${sessionId}`,
    whatsappSessionLandings: (sessionId: string) => `/admin/whatsapp-sessions/${sessionId}/landings`,
    linkCashierSession: (sessionId: string) => `/admin/whatsapp-sessions/${sessionId}/link`,
    landingSessions: (landingId: string) => `/admin/landings/${landingId}/sessions`,
    landings: "/admin/landings",
    landingById: (landingId: string) => `/admin/landings/${landingId}`,
    landingDisable: (landingId: string) => `/admin/landings/${landingId}/disable`,
    landingEnable: (landingId: string) => `/admin/landings/${landingId}/enable`,
    leads: "/admin/leads",
    leadHistory: (leadId: string) => `/admin/leads/${leadId}/history`,
    conversions: "/admin/conversions",
    conversionsTotals: "/admin/conversions/totals",
    statsSummary: "/admin/stats/summary",
    statsByCashier: "/admin/stats/cashiers",
    statsFundsSeries: "/admin/stats/funds-series",
    admins: "/admin/admins",
    adminById: (adminId: string) => `/admin/admins/${adminId}`,
    adminStatus: (adminId: string) => `/admin/admins/${adminId}/status`,
    landingFallbackPhones: (landingId: string) =>
      `/admin/landings/${landingId}/fallback-phones`,
    landingFallbackPhone: (landingId: string, id: string) =>
      `/admin/landings/${landingId}/fallback-phones/${id}`,
    autoConversionTriggerPhrase: "/admin/settings/auto-conversion-trigger-phrase",
    settingByKey: (key: string) => `/admin/settings/${key}`,
  },
  cashier: {
    sessions: "/cashier/sessions",
    currentSession: "/cashier/sessions/current",
    sessionStart: "/cashier/sessions/start",
    sessionFinish: "/cashier/sessions/finish",
    createConversion: (leadId: string) => `/cashier/leads/${leadId}/convert`,
    searchLeads: "/cashier/leads/search",
    conversions: "/cashier/conversions",
    runtimeState: "/cashier/runtime-state",
    account: "/cashier/account",
    whatsappLinkState: "/cashier/whatsapp/link-state",
    whatsappLinkReset: "/cashier/whatsapp/link/reset",
    whatsappLinkStatus: "/cashier/whatsapp/link/status",
    whatsappLinkComplete: "/cashier/whatsapp/link/complete",
    // Batch 5 — per-session cashier endpoints
    mySessions: "/cashier/me/sessions",
    mySession: (sessionId: string) => `/cashier/me/sessions/${sessionId}`,
    mySessionLink: (sessionId: string) => `/cashier/me/sessions/${sessionId}/link`,
    mySessionRefresh: (sessionId: string) => `/cashier/me/sessions/${sessionId}/refresh`,
    mySessionResetRefresh: (sessionId: string) => `/cashier/me/sessions/${sessionId}/reset-refresh`,
    mySessionStatus: (sessionId: string) => `/cashier/me/sessions/${sessionId}/status`,
  },
};
