export const endpoints = {
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    logout: "/auth/logout",
  },
  admin: {
    account: "/admin/account",
    cashiers: "/admin/cashiers",
    cashierById: (cashierId: string) => `/admin/cashiers/${cashierId}`,
    cashierDisable: (cashierId: string) => `/admin/cashiers/${cashierId}/disable`,
    cashierEnable: (cashierId: string) => `/admin/cashiers/${cashierId}/enable`,
    cashierLandings: (cashierId: string) => `/admin/cashiers/${cashierId}/landings`,
    landings: "/admin/landings",
    landingById: (landingId: string) => `/admin/landings/${landingId}`,
    landingDisable: (landingId: string) => `/admin/landings/${landingId}/disable`,
    landingEnable: (landingId: string) => `/admin/landings/${landingId}/enable`,
    leads: "/admin/leads",
    conversions: "/admin/conversions",
    statsSummary: "/admin/stats/summary",
    statsByCashier: "/admin/stats/cashiers",
    statsFundsSeries: "/admin/stats/funds-series",
  },
  cashier: {
    sessions: "/cashier/sessions",
    currentSession: "/cashier/sessions/current",
    sessionStart: "/cashier/sessions/start",
    sessionFinish: "/cashier/sessions/finish",
    createConversion: (leadId: string) => `/cashier/leads/${leadId}/convert`,
    searchLeads: "/cashier/leads/search",
    conversions: "/cashier/conversions",
    leads: "/cashier/leads",
    runtimeState: "/cashier/runtime-state",
    account: "/cashier/account",
    whatsappLinkState: "/cashier/whatsapp/link-state",
    whatsappLinkStart: "/cashier/whatsapp/link/start",
    whatsappLinkRefresh: "/cashier/whatsapp/link/refresh",
    whatsappLinkReset: "/cashier/whatsapp/link/reset",
    whatsappLinkStatus: "/cashier/whatsapp/link/status",
    whatsappLinkComplete: "/cashier/whatsapp/link/complete",
  },
};
