-- AlterEnum
ALTER TYPE "LEADS_STATUS" ADD VALUE IF NOT EXISTS 'EXPIRED';

-- AlterTable
ALTER TABLE "Leads"
ADD COLUMN "expiresAt" TIMESTAMP(3),
ADD COLUMN "matchedAt" TIMESTAMP(3);

UPDATE "Leads"
SET "expiresAt" = NOW() + INTERVAL '24 hours'
WHERE "expiresAt" IS NULL;

ALTER TABLE "Leads"
ALTER COLUMN "expiresAt" SET NOT NULL;
